### ISSUE TITLE
window redraw breaks in original split

### ISSUE THREAD

**Issue by mattmartini** [tpope/vim-db#4]
When I have a  document open (ie Gemfile) and I do a :DB command (:DB select * from users;) a new split window is created with the results.  The original window is blanked out (no text is visible).  When I jump back to the original window the line under the cursor will appear.  Moving up or down in the file causes each line to reappear as the cursor gets there.  If I close the DB split, the whole original window is redrawn correctly.

**Comment by timvisee** [comment]
I'm experiencing the same.

Disabling things like `:set nolazyredraw` doesn't have any effect either.

**Comment by timvisee** [comment]
@tpope With adapters, I assume you mean `vim-db` database adapters. In my instance, it's happening both for `mysql` and for `sqlite`. I have not tried others.

Adding `redraw` on the line you've noted does solve the issue for me.
However, this still causes the screen to flicker as the screen is somehow cleared after which it is redrawn again because of the added `redraw` statement.

**Comment by tpope** [comment]
You're right, the annoying flicker is why I didn't want to take that approach. I've pushed up something a bit different. Please report back on any issues, as I'm worried it won't work on Windows or other weird shell setups.

**Comment by timvisee** [comment]
@tpope Awesome! Your last change did solve the issue for me.

I can't report about Windows however. I'm using a Linux machine, with a vim instance inside tmux which I use through the alacritty terminal emulator.
